[package]
name = "emu"
version = "0.1.0"
edition = "2021"

[dependencies]

pixels = "0.13.0"
byteorder = "1"
env_logger = "0.10"
error-iter = "0.4"
getrandom = "0.2"
clipline = "0.1.1"
log = "0.4"
randomize = "3"
winit = "0.28"
winit_input_helper = "0.14"